language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py27
addons:
  apt:
    packages:
      - python-imdbpy
      - python-notify2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv env; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . env/bin/activate; fi
install:
  - pip install -r requirements.txt
script:
  - cd $TRAVIS_BUILD_DIR/
  - flake8 --select E,W --max-line-length=140 --ignore E722 jarviscli/
  - cd jarviscli/
  - python -m unittest discover
